---
title: "Overview"
---
    
Here are the overviews for each module of the class.

## Module01. Getting started

### Learning objectives

1. To understand the historical roots of the SAS program.

2. To identify an access method for SAS that works for you.

### SAS code that you will learn

+ data
+ delimiter
+ filename
+ infile
+ input
+ ods
+ proc print
+ run
+ title

### Videos and handouts

Please note that the code shown in these videos will not run exactly the same on your system. It might be something as simple as changing the path or the drive letter or both on the ods, libname, or filename statements. If you have any trouble, let me know.

+ V01-01. Getting started (16 minutes). 
  + Available in [Panopto format](https://umkc.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=3c8860e3-ec58-4873-ba83-aa68012a84c2).
  + Slides with speaker notes available in [pdf format](https://github.com/pmean/introduction-to-SAS/blob/master/basics1/results/getting-started.pdf).

+ V01-02. History of SAS (8 minutes). 
  + Available in [Panopto format](https://umkc.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=ba88be23-73d8-4804-ada4-aa73011ac94a). 
  + Slides with speaker notes are not available.

+ V01-03. Your first SAS program (10 minutes). 
  + Available in [Panopto format](https://umkc.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=671572b5-a25a-46e0-8d85-aa730122496b).
  + Slides with speaker notes are not available.
  + your-first-program.sas is available in [text format](https://github.com/pmean/introduction-to-SAS/tree/master/basics1/src/your-first-program.sas).

+ V01-04. Storing SAS datasets using libname (12 minutes). 
  + Available in [Panopto format](https://umkc.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=a8dbb622-2d61-41a7-b6a4-aa7301264e3e).
  + Slides with speaker notes are not available.
  + permanent-storage.sas is available in [text format](https://github.com/pmean/introduction-to-SAS/tree/master/basics1/src/permanent-storage.sas).
  + re-use.sas is available in [text format](https://github.com/pmean/introduction-to-SAS/tree/master/basics1/src/re-use.sas).

+ V01-05. Storing SAS output using ODS (15 minutes). 
  + Available in [Panopto format](https://umkc.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=cebf1a98-06bf-41e0-9be1-aa7301384dc6).
  + Slides with speaker notes are not available.
  + saved-pdf.sas is available in [text format](https://github.com/pmean/introduction-to-SAS/tree/master/basics1/src/saved-pdf.sas).
  + saved-html.sas is available in [text format](https://github.com/pmean/introduction-to-SAS/tree/master/basics1/src/saved-html.sas).

+ V01-06. Reading external data using infile and filename (13 minutes). 
  + Available in [Panopto format](https://umkc.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=faeefa60-c4ed-4d5b-a959-aa73013ea6af).
  + Slides with speaker notes are not available.
  + input-text.sas is available in [text format](https://github.com/pmean/introduction-to-SAS/tree/master/basics1/src/input-text.sas).
  
### Discussion board

Please briefly introduce yourself. Tell us a bit about yourself professionally, and optionally tell us one thing that is not related to your work or your career. Also optional, but greatly appreciated, would be a picture of yourself.                                                                            

Submit your discussion comments [here](https://umkc.instructure.com/courses/59353/discussion_topics/186810).   

### Homework

Take the code in your-first-program.sas and run it on your system. If you get an error message that you can't fix, document that error message in the text box. You will get full credit for any reasonable attempt to get the program to run. If your program ran successfully, describe your difficulties (if any) in getting the program to run. 

THe format in which you submit your assignment is also very flexible. The best thing to send me would be a PDF of the output window combined with a PDF of your code. Second best would be two separate PDF files, one for the output and one for the code. I like the PDF format, but you can submit in any reasonable format, if have difficulty producing a PDF file. There are at least a dozen different ways of producing a PDF file and I probably know about half of them. So don't be afraid to ask questions about this.

Submit your assignment [here](https://umkc.instructure.com/courses/59353/assignments/228704).

## Module02. Reading a variety of formats

### Learning objectives

1. To read delimited text files

2. To read fixed width files

3. To read files with variable names in the first row

### SAS code that you will learn

+ delimiter
+ filename
+ proc import
  + getnames

### Videos and handouts

+ V02-01. Importing a wide range of data formats, part 1 (7 minutes). 
  + Available in [Panopto format](https://umkc.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=6de8440a-1bd4-4d2e-9631-aa7f015b2953).
  + Slides with speaker notes available in [pdf format](https://github.com/pmean/introduction-to-SAS/blob/master/basics2/src/importing-speaker-notes.pdf).

+ V02-02. Importing a wide range of data formats, part 2 (23 minutes). 
  + Available in [Panopto format](https://umkc.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=4954f8af-d8be-4657-bc24-aa7f015edf92).
  + Slides with speaker notes available above.

+ V02-03. Importing a wide range of data formats, part 3 (12 minutes). 
  + Available in [Panopto format](https://umkc.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=0ce9339f-f3c9-4bb3-908e-aa790131a2a9).
  + Slides with speaker notes available above.

+ V02-03. Importing a wide range of data formats, part 3 (12 minutes). 
  + Available in [Panopto format](https://umkc.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=0ce9339f-f3c9-4bb3-908e-aa790131a2a9).
  + Slides with speaker notes available above.

+ V02-04. Importing a wide range of data formats, part 4 (). 
  + Available in [Panopto format]().
  + Slides with speaker notes available above.

### Discussion board

I'd like some brief feedback to the videos you just watched. Keep it short. One or two sentences per question is fine. You can also say something briefer like "I agree with [other student]". If you found everything confusing or nothing confusing, just respond with the word "everything" or "nothing." Please don't spend more than a minute on this assignment. I just want a quick reaction.

1. What was the most important thing you learned in these videos?

2. What was the one thing that you found confusing?

3. What would you like to see covered next?

Submit your discussion comments [here](https://umkc.instructure.com/courses/59353/discussion_topics/186808).

### Homework

Read the data in the file sleep.txt or in the file sleep_modified.txt and print out the first ten rows of data. Include your code and your output in a single PDF file.

Submit your assignment [here](https://umkc.instructure.com/courses/59353/assignments/228705).

## Module03. Working with mostly continuous variables

### Learning objectives

1. To produce means and standard deviations

2. To create and manipulate missing value

3. To draw histograms and scatterplots

### SAS code that you will learn

+ if ... then
+ proc corr
  + noprint
  + output
+ proc format
  + values
+ proc means
  + nmiss
+ proc sgplot
  + histogram
    + binstart
    + binwidth
  + pbspline
  + reg
  + scatter
+ proc sort
  + by
    + descending
+ set
 

### Videos and handouts

+ V03-01. libname, filename, print (21 minutes). 
  + Available in [Panopto format](https://umkc.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=97d00c33-5197-4a0f-9f16-aa6f014da077).
  + Slides with speaker notes available in [pdf format](https://umkc.instructure.com/courses/59353/files/2399372).

+ V03-02. Variable names, proc means (10 minutes). 
  + Available in [Panopto format](https://umkc.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=996a7c89-0e5a-4118-92ce-aa6f015599d0).
  + Slides with speaker notes available above.

+ V03-03. Missing values (15 minutes). 
  + Available in [Panopto format](https://umkc.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=d5794c7d-3933-488c-bc3c-aa6f015a3d7c).
  + Slides with speaker notes available above.

+ V03-04. Simple transformations, histograms (9 minutes). 
  + Available in [Panopto format](https://umkc.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=17b9a21d-df54-4705-928d-aa6f016161d4).
  + Slides with speaker notes available above.

+ V03-05. Correlations and scatterplots (25 minutes). 
  + Available in [Panopto format](https://umkc.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=bd9a8ec9-6cee-4f5a-b83b-aa6f0165b591).
  + Slides with speaker notes available above.

### Discussion board

I'd like some brief feedback to the videos you just watched. Keep it short. One or two sentences per question is fine. You can also say something briefer like "I agree with [other student]". If you found everything confusing or nothing confusing, just respond with the word "everything" or "nothing." Please don't spend more than a minute on this assignment. I just want a quick reaction.

1. What was the most important thing you learned in these videos?

2. What was the one thing that you found confusing?

3. What would you like to see covered next?

Submit your discussion comments [here](https://umkc.instructure.com/courses/59353/discussion_topics/186809).

### Homework

Homework03.

Having reviewed these analyses, I would like
you to turn in some simple analyses that you
run on a fresh data set. This homework
assignment will be graded pass/fail.

There is a second data set on sleep in
mammals. You can find a brief description of
this data set at

--> http://www.statsci.org/data/general/sleep.html

and you can download the actual data at

--> http://www.statsci.org/data/general/sleep.txt

For every question, include the relevant SAS
output and a brief written commentary explaining
what the results mean. When you send your
answers, please include the original questions.

1. Notice that there is a huge range in body
weight. Display the information for the
smallest and the largest mammals.

2. Which variables have missing data?

3. Calculate the mean and standard deviation
for TotalSleep.

4. Draw a histogram for the BodyWt variable.
Note that this variable is highly skewed.
Re-draw the histogram on the log scale.
For exta credit, relabel the axes with values
at 0.001, 0.01, etc.

5. Calculate the ratio of BrainWt to BodyWt
and express it as a percentage. Be sure to
convert grams to kilograms (or vice versa)
before computing the ratio. What animal has
the smallest/largest ratio?

6. Do bigger animals sleep longer or live
longer? Show your results using a correlation
coefficient.

7. Do animals who have high degrees of
Predation, Exposure, or Danger sleep less?
Show your results using a plot and a trendline.

8. Place all the key results into a document
and copy the original questions and include
your own written answer along with the
appropriate supporting tables or graphs.
Do NOT submit uneditted and unannoted
SAS output. You can use any program to
prepare the output, but convert it to a PDF
format before submission. If you have any
difficulty producing a PDF document, please
talk to me.

Submit your assignment [here](https://umkc.instructure.com/courses/59353/assignments/228706).

## Module04. Working with mostly categorical variables

### Learning objectives



### SAS code that you will learn


### Videos and handouts

+ V04-01.  ( minutes). 
  + Available in [Panopto format]().
  + Slides with speaker notes available in [pdf format]().

+ V04-02.  ( minutes). 
  + Available in [Panopto format]().
  + Slides with speaker notes available above.

### Discussion board

I'd like some brief feedback to the videos you just watched. Keep it short. One or two sentences per question is fine. You can also say something briefer like "I agree with [other student]". If you found everything confusing or nothing confusing, just respond with the word "everything" or "nothing." Please don't spend more than a minute on this assignment. I just want a quick reaction.

1. What was the most important thing you learned in these videos?

2. What was the one thing that you found confusing?

3. What would you like to see covered next?

Submit your discussion comments [here]().

### Homework



Submit your assignment [here]().


## Module05. Working with a mix of continuous and categorical variables

### Learning objectives



### SAS code that you will learn


### Videos and handouts

+ V05-01.  ( minutes). 
  + Available in [Panopto format]().
  + Slides with speaker notes available in [pdf format]().

+ V05-02.  ( minutes). 
  + Available in [Panopto format]().
  + Slides with speaker notes available above.

### Discussion board

I'd like some brief feedback to the videos you just watched. Keep it short. One or two sentences per question is fine. You can also say something briefer like "I agree with [other student]". If you found everything confusing or nothing confusing, just respond with the word "everything" or "nothing." Please don't spend more than a minute on this assignment. I just want a quick reaction.

1. What was the most important thing you learned in these videos?

2. What was the one thing that you found confusing?

3. What would you like to see covered next?

Submit your discussion comments [here]().

### Homework



Submit your assignment [here]().



## Module06. 

### Learning objectives



### SAS code that you will learn


### Videos and handouts

+ V06-01.  ( minutes). 
  + Available in [Panopto format]().
  + Slides with speaker notes available in [pdf format]().

+ V06-02.  ( minutes). 
  + Available in [Panopto format]().
  + Slides with speaker notes available above.

### Discussion board

I'd like some brief feedback to the videos you just watched. Keep it short. One or two sentences per question is fine. You can also say something briefer like "I agree with [other student]". If you found everything confusing or nothing confusing, just respond with the word "everything" or "nothing." Please don't spend more than a minute on this assignment. I just want a quick reaction.

1. What was the most important thing you learned in these videos?

2. What was the one thing that you found confusing?

3. What would you like to see covered next?

Submit your discussion comments [here]().

### Homework



Submit your assignment [here]().




