---
title: "MEDB 5510, Clinical Research Methods, Syllabus"
output: html_document
---

```{r part-a, child="data/syllabus-part-a-5510.md"}
```

```{r part-b, child="data/syllabus-part-b-all-classes.md"}
```

```{r part-c, child="data/syllabus-part-c-5510.md"}
```

```{r part-d, child="data/syllabus-part-d-all-classes.md"}
```

```{r part-e, child="data/syllabus-part-e-5510.md"}
```

```{r objectives01, child="data/5510-01-objectives.md"}
```

```{r objectives02, child="data/5510-02-objectives.md"}
```

```{r objectives03, child="data/5510-03-objectives.md"}
```

```{r objectives04, child="data/5510-04-objectives.md"}
```

```{r objectives05, child="data/5510-05-objectives.md"}
```

```{r objectives06, child="data/5510-06-objectives.md"}
```

```{r objectives07, child="data/5510-07-objectives.md"}
```

```{r objectives08, child="data/5510-08-objectives.md"}
```

```{r objectives09, child="data/5510-09-objectives.md"}
```

```{r objectives10, child="data/5510-10-objectives.md"}
```

```{r objectives11, child="data/5510-11-objectives.md"}
```

```{r objectives12, child="data/5510-12-objectives.md"}
```

```{r objectives13, child="data/5510-13-objectives.md"}
```

```{r part-f, child="data/syllabus-part-f-all-classes.md"}
```

This document was written on 2020-08-26 and last modifed on `r Sys.Date()`.