---
title: "MEDB 5510, Clinical Research Methods. Overview"
---
    
### General information
    
This file was created by Steve Simon using R Markdown on 2021-01-08 and last updated on `r Sys.Date()`. You can find the [source code](https://github.com/classes-medb/classes-medb.github.io/blob/master/5510-overview.Rmd) on my github repository, [classes-medb](https://github.com/classes-medb).

This class is taught using the Canvas learning management system. Access to Canvas is limited to me and students currently enrolled. If you have access, the main page for the Canvas site for Fall Semester 2020 is found [here](https://umkc.instructure.com/courses/58364).

The resources on this website will be generally consistent with those on Canvas. If you find any major discrepancies, please bring them to my attention. The information on Canvas takes precedence over the information presented here.

### Syllabus

The syllabus is available on [Canvas](https://umkc.instructure.com/courses/58364/assignments/syllabus) or in [html format](5510-syllabus.html). These should be identical, but if there are any discrepancies, the Canvas site takes precedence.

Here are the overviews for each module of the class.

```{r, echo=FALSE}
suppressMessages(suppressWarnings(library(magrittr)))
path <- "https://raw.githubusercontent.com/pmean/classes/master/clinical-research-methodology/data/"
full_text <- NULL
for (i in c("02", "03")) {
  full_text %<>% append(paste0("### Module", i))
  fn <- paste0(path, "handouts", i, ".md")
  full_text %<>% append(readLines(fn, warn=FALSE)[-(1:3)])
}
full_text <- paste0(full_text, collapse="\n\n")
```

`r full_text`

