---
title: "Steve Simon's MEDB classes"
---
    
This website provides information about the courses that Steve Simon teaches at the University of Missouri-Kansas City. All of these classes start with the four letters MEDB, whose meaning has been lost to antiquity.

All of the information on this website and as well as the assignment, code, and handouts for these classes are included in a [github site](https://github.com/classes-medb).

This site has the following repositories:

+ [classes-medb.github.io](https://github.com/classes-medb/classes-medb.github.io): which contains the R Markdown files needed to create this website.
+ [5505](https://github.com/classes-medb/5505) which contains the assignments, code, data, and handouts used in MEDB 5505, Introduction to R.
+ [5507](https://github.com/classes-medb/5507) which contains the assignments, code, data, and handouts used in MEDB 5507, Introduction to SAS.
+ [5508](https://github.com/classes-medb/5508) which contains the assignments, code, data, and handouts used in MEDB 5508, Introduction to SQL.
+ [5510](https://github.com/classes-medb/5510) which contains the assignments, code, data, and handouts used in MEDB 5510, Clinical Research Methodology.

All of these repositories are rapidly evolving. Not all the assignments, code, data, and handouts are available for every repository. Eventually, things will settle down.