---
title: "MEDB 5510, Clinical Research Methodology, Syllabus, Part E"
---

### Specific Information about this class

#### Required and Recommended Materials	
+ ...

#### Course Expectations, Course Policies, Requirements and Standards for Student Coursework and Student Behavior
+ You are expected to do your homework independently. You can seek help from your instructors, from colleagues, or from the Internet to review your writing, but you cannot have them write for you. 

#### Evaluation and Grading
+ Students will be required to post messages on the Canvas discussion boards, take brief quizzes on Canvas, and submit homework assignments in PDF format on Canvas. Your work is due on the specified date. We need to keep the class on the same time schedule for a variety of reasons. If illness, family issues, work responsibilities, or other commitments prevent you from completing on time, please contact me before the due date. Late submission without prior notice will receive a one point deduction. If you find yourself repeatedly falling behind on quizzes and assignments, it would be good to set up a videoconfernce with one or both of us to discuss this.
+ This course is ...

#### Final Exam
+ This is no final exam. Your final project needs to be completed prior to the last day of classes (2021-05-07, Friday).

### Description of Course Topics, Assignments, Requirements and Assignment deadlines

#### Module01

```{r child="5510-01-overview.md"}
```

Assignments are still being finalized but will be available soon in the [course overview](https://pmean.github.io/docs/5505-overview.Rmd) for details on individual assignments.
