---
title: "MEDB 5508, Introduction to SQL, Syllabus, Part C"
---

### Common Questions about Course Details

#### Catalog Course ID 	
+ MEDB 5508-0001 (15782)

#### How many Credit Hours will I receive after successfully completing this course?	
+ 2

#### What are the Meeting Times and Location for the course?	
+ This is an online class with no pre-specified meeting times.

#### What is the format of this course?	
+ Asynchronous online.

#### What is this course about (Course Description)?	 
+ SQL ...

#### What are the knowledge, skills or perspectives (Student Learning Outcomes) that I will gain from the course?	
+ SQL ...

#### Are there Pre-requisites/Co-requisites that are key to my success in this course?
+ This course will provide a working familiarity with SQL. Students are not expected to have advanced programming or statistical analysis skills. A basic understanding of statistical terminology and a working familiarity with computer-based data files (e.g., Excel) is necessary.
