---
title: "MEDB 5505, Introduction to R, Syllabus, Part E"
---

### Specific Information about this class

#### Required and Recommended Materials	
+ There is NO required textbook for this class. A recommended textbook is ...

#### Course Expectations, Course Policies, Requirements and Standards for Student Coursework and Student Behavior
+ You are expected to do your homework independently. You can seek help from your instructors, from colleagues, or from the Internet to help decode an error message that you don't understand. You can adapt code that you find on the Internet. We recommend that you acknowledge the source for that code in the comments of your program, but this is not required.

#### Evaluation and Grading
+ Students will be required to post messages on the Canvas discussion boards, take brief quizzes on Canvas, and submit homework assignments in PDF format on Canvas. Your work is due on the specified date. We need to keep the class on the same time schedule for a variety of reasons. If illness, family issues, work responsibilities, or other commitments prevent you from completing on time, please contact me before the due date. Late submission without prior notice will receive a one point deduction. If you find yourself repeatedly falling behind on quizzes and assignments, it would be good to set up a videoconfernce with one or both of us to discuss this.
+ This course is grade Credit/No Credit (Pass/Fail). Students who complete at least 80% of the regular coursework and sucessfully complete the final project will receive credit for the course.

#### Final Exam
+ This is no final exam. Your final project needs to be completed prior to the last day of classes (2021-05-07, Friday).

### Description of Course Topics, Assignments, Requirements and Assignment deadlines

Please refer to the [course overview](https://pmean.github.io/docs/5505-overview.Rmd).
